project:
  type: website
  output-dir: docs

website:
  title: "Tika Ram Gurung"
  description: "Personal academic website of Tika Ram Gurung, Ph.D. candidate at University of Nebraska-Lincoln, specializing in glacier mass balance, hydroclimate, heatwaves, and climate modeling in High Mountain Asia."
  open-graph: true
  twitter-card: true
  site-url: "https://tikagurung.github.io/tika-r-gurung-github.io/"
  favicon: "favicon.ico"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
      - href: blogs.qmd
        text: BLOGS
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/TikaGurung
      - icon: linkedin
        href: https://www.linkedin.com/in/tika-ram-gurung-55a743a3/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    title-block-banner: false
